### PR TITLE
Theming2

### PR DESCRIPTION
**Pull request by dabush**
More changes to appearance of site

### CODE REVIEW

**Comment by mwidner** [comment]
I'm not seeing the previous layout for text nodes. Screenshot: 
screen shot 2017-07-27 at 10 43 40 am

Is this what it's supposed to look like?

**Comment by dabush** [comment]
Nope, for some reason it won't let me override the display suite settings, so I've had to do that on the site itself. Any idea why it keeps overriding my display suite customizations? I've added it to the feature..

**Comment by mwidner** [comment]
Hmm.. If we don't already, probably need to add the Strongarm module and include the DS variables in the feature.

**Comment by dabush** [comment]
good call Mike! it's in there now. I'll remember that for the future

**Pull request merged**
